name: core
description: "Fornece padronização de métodos dos pacotes da aplicação"
version: 0.0.1
homepage:
isar_version: &isar_version 3.3.0-dev.1 # define the version to be used


environment:
  sdk: ^3.5.0
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.2
  isar_community: 
    version: *isar_version
  isar_community_flutter_libs: # contains Isar Core
    version: *isar_version
  date_format_field: ^0.1.0
  mask_text_input_formatter: ^2.9.0
  cpf_cnpj_validator: ^2.0.0
  path_provider: ^2.1.5
  equatable: ^2.0.7
  mockito: ^5.4.4
  flutter_bloc: ^9.0.0
  bloc_test: ^10.0.0
  get_it: ^8.0.3
  http_interceptor: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  build_runner: any
  

flutter:
